### ISSUE TITLE
Installation of TVTB for R3.2.2

### ISSUE THREAD

**Issue by chunjie-sam-liu** [kevinrue/TVTB#4]
Are there any methods to install TVTB package for R3.2.2?

I tried to install, but failed for "package 'TVTB' requires R >= 3.4".

**Comment by kevinrue** [comment]
Note that the [release version of **TVTB**](http://bioconductor.org/packages/release/bioc/html/TVTB.html) only requires `R (>= 3.3)`. The reason is that **TVTB** depends on other packages that also require `R (>= 3.3)`, for instance [S4Vectors](http://bioconductor.org/packages/release/bioc/html/S4Vectors.html):

    Depends	R (>= 3.3.0), methods, utils, stats, stats4, BiocGenerics(>= 0.15.10)

In other words, even if I accepted earlier releases of R, dependency packages such as ***S4Vectors* would still request `R (>= 3.3.0)`.

Do you wish to install the [devel version of TVTB](http://bioconductor.org/packages/devel/bioc/html/TVTB.html)
In that case, please note that some recent features introduced in the devel version of **TVTB** depend on fixes introduced in the [devel branch](http://bioconductor.org/developers/how-to/useDevel/) of Bioconductor (3.5), which is targeted for [R, version 3.4.0 Under development (2017-01-28)](https://cran.r-project.org/doc/manuals/r-devel/R-admin.html); hence the requirement.

Using **TVTB** with older releases of R/Bioconductor packages creates the risk of undesirable/unexpected behaviour/results.

If possible, I suggest that you upgrade your R installation to `R (>= 3.3)` to benefit of the most recent stable release version of Bioconductor that includes **TVTB** and dependencies.

Best regards.
Kevin
